#!/usr/bin/env python3
"""doc-template-styler - single entry point.

GENERATED by scripts/build_publish.py from the skill's development tree; the
scripts below are embedded VERBATIM (one string each) so the published skill
is two files instead of seventy. Nothing is downloaded or fetched: the code
you read here is the code that runs. `python scripts/docstyler.py --help`.
"""

SOURCES = {}

# ======================================================================
# embedded: scripts/render_doc.py
# ======================================================================
SOURCES['render_doc'] = r'''#!/usr/bin/env python3
"""Render a document model into a user-supplied HTML template.

The model is the canonical intermediate format (see references/content-model.md).
Block markup is generated here so the same template always yields the same
classes. Two things are injected rather than written into the template:

  * the palette, as one :root / [data-theme] override, so the template's theme
    toggle keeps working across every palette;
  * bilingual text, as <span class="t-vi">/<span class="t-en"> pairs, so the
    template's language switch has something to switch between.

A third, small style block (`doc-blocks`) carries the rules for the blocks no
template styles on its own - code, figures, nested lists - plus print rules.

assets/editor/src/core.js mirrors every rendering function here; the node test
suite checks the two against goldens generated from this file.
"""

from __future__ import annotations

import argparse
import base64
import html
import json
import mimetypes
import re
import sys
import unicodedata
from pathlib import Path

PLACEHOLDER_RE = re.compile(r"\{\{\s*([A-Za-z0-9_.-]+)\s*\}\}")
PREFERRED_ENTRIES = ("template.html", "index.html", "template.htm", "index.htm")
LANG_KEYS = ("vi", "en")
TEMPLATE_ID_RE = re.compile(r'\bid="([^"{}]+)"')

# Inline formatting: a small, safe subset of Markdown. Code spans and backslash
# escapes are set aside first so nothing inside them is formatted.
INLINE_PROTECT_RE = re.compile(r"\\([\\`*_\[\]()#>+\-.!|])|`([^`\n]+)`")
LINK_RE = re.compile(r"\[([^\]\n]+)\]\(([^)\s]+)\)")
BOLD_RE = re.compile(r"\*\*(\S(?:[^\n]*?\S)?)\*\*")
EM_RE = re.compile(r"\*(\S(?:[^\n*]*?\S)?)\*")
UNDER_RE = re.compile(r"(^|[^A-Za-z0-9_])_(\S(?:[^\n_]*?\S)?)_(?![A-Za-z0-9_])")
# no scheme at all (a relative path), or one of these; javascript:, data: and
# the like stay as literal text
SAFE_URL_RE = re.compile(r"^(?:https?:|mailto:|tel:|#|[^:]*$)", re.IGNORECASE)
STASH_RE = re.compile("\x00(\\d+)\x00")

# Styles for the blocks templates do not style themselves. Class selectors
# only, so a template that does style them still wins on specificity.
BLOCK_CSS = (
    ".doc-code{margin:1.1em 0;padding:14px 16px;overflow-x:auto;"
    "border:1px solid color-mix(in oklab,var(--brand-ink,#1b1b1b) 16%,transparent);border-radius:10px;"
    "background:color-mix(in oklab,var(--doc-surface,#f4f4f4) 90%,var(--brand-ink,#1b1b1b));"
    "font:.86em/1.55 ui-monospace,SFMono-Regular,Consolas,\"Liberation Mono\",monospace;white-space:pre;tab-size:4}"
    ".doc-code code{background:none;padding:0;border-radius:0;color:inherit;font:inherit;white-space:inherit}"
    ".doc-figure{margin:1.4em 0;text-align:center}"
    ".doc-figure img{max-width:100%;height:auto;border-radius:10px}"
    ".doc-figure figcaption{margin-top:.5em;font-size:.86em;opacity:.75}"
    ".doc-figure--missing{padding:18px;border:1px dashed currentColor;border-radius:10px;opacity:.7}"
    ".doc-section li>ul,.doc-section li>ol{margin:.25em 0}"
    ".doc-toc{margin:0 auto 2rem;padding:16px 20px;max-width:var(--maxw,860px);border:1px solid color-mix(in oklab,var(--brand-ink,#1b1b1b) 16%,transparent);border-radius:12px;background:var(--doc-surface,transparent)}"
    ".doc-toc__title{margin:0 0 .5em;font-weight:700;font-size:.8em;letter-spacing:.08em;text-transform:uppercase;color:var(--brand-primary,inherit)}"
    ".doc-toc ol{margin:0;padding-left:1.4em;columns:2 18em;column-gap:2em}"
    ".doc-toc li{margin:.2em 0;break-inside:avoid}"
    ".doc-toc a{color:inherit;text-decoration:none;border-bottom:1px dotted currentColor}"
    ".doc-toc a:hover{color:var(--brand-primary,inherit)}"
    ".doc-section{scroll-margin-top:16px}"
    "@media print{.doc-code{white-space:pre-wrap;overflow:visible}"
    ".doc-code,.doc-figure,.doc-table,.callout,.kv{break-inside:avoid}"
    ".doc-section h2,.doc-section h3{break-after:avoid}}"
)

# Used when --template is not given. The user chooses the template (SKILL.md
# step 3); this is only the fallback / recommended default.
SKILL_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TEMPLATE = SKILL_ROOT / "assets" / "templates" / "technext-shell"


def esc(value):
    return html.escape("" if value is None else str(value), quote=True)


def is_dual(value):
    return isinstance(value, dict) and any(key in value for key in LANG_KEYS)


def _emphasis(text):
    text = BOLD_RE.sub(r"<strong>\1</strong>", text)
    text = EM_RE.sub(r"<em>\1</em>", text)
    return UNDER_RE.sub(r"\1<em>\2</em>", text)


def inline(value, links=True):
    """Escape text, then apply **bold**, *italic*, `code` and [links](url).

    links=False renders a link as its label only - for places that are already
    inside an <a>, such as the table of contents.
    """
    if value is None:
        return ""
    text = str(value).replace("\x00", "")
    stash = []

    def keep(markup):
        stash.append(markup)
        return "\x00%d\x00" % (len(stash) - 1)

    def protect(match):
        if match.group(1) is not None:
            return keep(esc(match.group(1)))
        return keep("<code>%s</code>" % esc(match.group(2)))

    def link(match):
        label, url = match.group(1), match.group(2)
        if not SAFE_URL_RE.match(url):
            return match.group(0)
        label = _emphasis(label)
        if not links:
            return keep(label)
        return keep('<a href="%s">%s</a>' % (url, label))

    text = INLINE_PROTECT_RE.sub(protect, text)
    text = LINK_RE.sub(link, esc(text))
    text = _emphasis(text)
    while STASH_RE.search(text):
        text = STASH_RE.sub(lambda m: stash[int(m.group(1))], text)
    return text


def rt(value, links=True):
    """Rich text: inline-formatted string, or a bilingual span pair."""
    if is_dual(value):
        return "".join(
            '<span class="t-%s">%s</span>' % (code, inline(value.get(code), links))
            for code in LANG_KEYS
            if value.get(code) is not None
        )
    return inline(value, links)


def rt_verbatim(value):
    """Like rt() but with no inline formatting - for code."""
    if is_dual(value):
        return "".join(
            '<span class="t-%s">%s</span>' % (code, esc(value.get(code)))
            for code in LANG_KEYS
            if value.get(code) is not None
        )
    return esc(value)


def plain(value, lang="vi"):
    """One language only — for <title> and attributes, which cannot hold spans."""
    if is_dual(value):
        if value.get(lang) is not None:
            return str(value[lang])
        for code in LANG_KEYS:
            if value.get(code) is not None:
                return str(value[code])
        return ""
    return "" if value is None else str(value)


def has_dual(value):
    if is_dual(value):
        return True
    if isinstance(value, dict):
        return any(has_dual(v) for v in value.values())
    if isinstance(value, (list, tuple)):
        return any(has_dual(v) for v in value)
    return False


def find_entry(template_dir):
    for name in PREFERRED_ENTRIES:
        candidate = template_dir / name
        if candidate.is_file():
            return candidate
    html_files = sorted(p for p in template_dir.rglob("*.htm*") if p.is_file())
    if not html_files:
        raise FileNotFoundError("no .html file found in %s" % template_dir)
    return html_files[0]


def render_blocks(blocks):
    parts = []
    for block in blocks or []:
        kind = (block.get("type") or "paragraph").lower()
        if kind == "paragraph":
            parts.append("<p>%s</p>" % rt(block.get("text")))
        elif kind == "heading":
            level = min(max(int(block.get("level", 3)), 1), 6)
            parts.append("<h%d>%s</h%d>" % (level, rt(block.get("text")), level))
        elif kind == "list":
            parts.append(render_list(block.get("items"), block.get("ordered")))
        elif kind == "code":
            lang = block.get("lang")
            attr = ' data-lang="%s"' % esc(lang) if lang else ""
            parts.append('<pre class="doc-code"%s><code>%s</code></pre>' % (attr, rt_verbatim(block.get("text"))))
        elif kind == "image":
            parts.append(render_image(block))
        elif kind == "table":
            headers = block.get("headers") or []
            head = ""
            if headers:
                head = "<thead><tr>%s</tr></thead>" % "".join("<th>%s</th>" % rt(h) for h in headers)
            rows = "".join(
                "<tr>%s</tr>" % "".join("<td>%s</td>" % rt(c) for c in row)
                for row in block.get("rows") or []
            )
            parts.append('<table class="doc-table">%s<tbody>%s</tbody></table>' % (head, rows))
        elif kind == "quote":
            parts.append("<blockquote>%s</blockquote>" % rt(block.get("text")))
        elif kind == "callout":
            tone = esc(block.get("tone", "info"))
            title = block.get("title")
            heading = ""
            if title is not None:
                heading = '<p class="callout__title">%s</p>' % rt(title)
            parts.append(
                '<div class="callout callout--%s">%s<p>%s</p></div>'
                % (tone, heading, rt(block.get("text")))
            )
        elif kind == "kv":
            pairs = "".join(
                "<dt>%s</dt><dd>%s</dd>" % (rt(pair[0]), rt(pair[1]))
                for pair in block.get("pairs") or []
                if len(pair) >= 2
            )
            parts.append('<dl class="kv">%s</dl>' % pairs)
        elif kind == "hr":
            parts.append("<hr>")
        else:
            parts.append("<p>%s</p>" % rt(block.get("text")))
    return "\n".join(parts)


def is_nested_item(item):
    """A list item that carries its own sub-list: {"text": ..., "items": [...]}."""
    return isinstance(item, dict) and not is_dual(item)


def render_list(items, ordered):
    tag = "ol" if ordered else "ul"
    out = []
    for item in items or []:
        if is_nested_item(item):
            inner = rt(item.get("text"))
            if item.get("items"):
                inner += render_list(item.get("items"), item.get("ordered"))
            out.append("<li>%s</li>" % inner)
        else:
            out.append("<li>%s</li>" % rt(item))
    return "<%s>%s</%s>" % (tag, "".join(out), tag)


def render_image(block):
    """Only data: URIs are rendered as images - the output must work offline.
    render_doc.py embeds local files before rendering (embed_images)."""
    src = "" if block.get("src") is None else str(block.get("src"))
    alt = plain(block.get("alt"))
    caption = block.get("caption")
    cap = ""
    if caption is not None and caption != "":
        cap = "<figcaption>%s</figcaption>" % rt(caption)
    if src.startswith("data:image/"):
        return '<figure class="doc-figure"><img src="%s" alt="%s">%s</figure>' % (esc(src), esc(alt), cap)
    return '<figure class="doc-figure doc-figure--missing"><p>%s</p>%s</figure>' % (esc(alt or src or "image"), cap)


def section_id(section):
    heading = section.get("heading")
    if is_dual(heading):
        heading = plain(heading)
    return section.get("id") or _slug(heading or "section")


def section_ids(sections, reserved=()):
    """One id per section, unique within the document and never equal to an id
    the template already uses (#search, #hero ...), so every contents link
    lands on its own section."""
    seen = set(reserved)
    ids = []
    for section in sections or []:
        base = section_id(section)
        candidate, n = base, 2
        while candidate in seen:
            candidate = "%s-%d" % (base, n)
            n += 1
        seen.add(candidate)
        ids.append(candidate)
    return ids


TOC_TITLE = {"vi": "M\u1ee5c l\u1ee5c", "en": "Contents"}


def render_toc_nav(sections, reserved=(), lang="vi", bilingual=False):
    """A self-contained, clickable contents box - put at the top of the body
    when the template has no {{toc}} slot of its own, so every document gets
    one. Empty when no section has a heading."""
    items = []
    for section, sid in zip(sections or [], section_ids(sections, reserved)):
        heading = section.get("heading")
        if heading is None or heading == "":
            continue
        items.append('<li><a href="#%s">%s</a></li>' % (esc(sid), rt(heading, links=False)))
    if not items:
        return ""
    title = rt(TOC_TITLE) if bilingual else esc(TOC_TITLE.get(lang, TOC_TITLE["en"]))
    return ('<nav class="doc-toc" aria-label="%s"><p class="doc-toc__title">%s</p><ol>%s</ol></nav>'
            % (esc(TOC_TITLE.get(lang, TOC_TITLE["en"])), title, "".join(items)))


def adapt_template(document):
    """Give a template the slots it lacks: {{body}} before </body> if it has
    none. Returns (document, notes)."""
    notes = []
    if not re.search(r"\{\{\s*body\s*\}\}", document):
        if re.search(r"</body>", document, re.IGNORECASE):
            document = re.sub(r"</body>", "{{body}}\n</body>", document, count=1, flags=re.IGNORECASE)
        else:
            document += "\n{{body}}"
        notes.append("template has no {{body}} - content placed at the end of <body>")
    return document, notes


def render_toc(sections, reserved=()):
    links = []
    for section, sid in zip(sections or [], section_ids(sections, reserved)):
        heading = section.get("heading")
        if heading is None or heading == "":
            continue
        links.append('<a href="#%s">%s</a>' % (esc(sid), rt(heading, links=False)))
    return "\n".join(links)


def render_sections(sections, reserved=()):
    parts = []
    for section, sid in zip(sections or [], section_ids(sections, reserved)):
        heading = section.get("heading")
        level = min(max(int(section.get("level", 2)), 1), 6)
        head = ""
        if heading is not None and heading != "":
            head = "<h%d>%s</h%d>" % (level, rt(heading), level)
        parts.append(
            '<section class="doc-section" id="%s">\n%s\n%s\n</section>'
            % (esc(sid), head, render_blocks(section.get("blocks")))
        )
    return "\n".join(parts)


def _slug(text):
    """ASCII slug that keeps Vietnamese readable: "Kết quả" -> "ket-qua"."""
    text = unicodedata.normalize("NFD", str(text))
    text = re.sub("[̀-ͯ]", "", text).replace("đ", "d").replace("Đ", "D")
    slug = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    return slug or "section"


def template_ids(document):
    return sorted(set(TEMPLATE_ID_RE.findall(document)))


def block_style():
    return '<style id="doc-blocks">%s</style>' % BLOCK_CSS


def inject_blocks(document):
    if "</head>" in document:
        return document.replace("</head>", block_style() + "\n</head>", 1)
    return block_style() + "\n" + document


def _walk_blocks(blocks):
    for block in blocks or []:
        if isinstance(block, dict):
            yield block


def embed_images(model, base_dir):
    """Turn image blocks that point at local files into data: URIs, in place.
    Remote images are never fetched; they are reported so the user can supply
    the file. Returns a list of warnings."""
    warnings = []
    for section in model.get("sections") or []:
        for block in _walk_blocks(section.get("blocks")):
            if (block.get("type") or "").lower() != "image":
                continue
            src = str(block.get("src") or "")
            if not src or src.startswith("data:"):
                continue
            if re.match(r"^[a-z][a-z0-9+.-]*://", src, re.IGNORECASE):
                warnings.append("image %s is remote - not embedded (the file must work offline); "
                                "download it and point src at the local file" % src)
                continue
            path = Path(src).expanduser()
            if not path.is_absolute():
                path = Path(base_dir) / path
            if not path.is_file():
                warnings.append("image %s not found - rendered as its alt text" % src)
                continue
            mime = mimetypes.guess_type(path.name)[0] or ""
            if not mime.startswith("image/"):
                warnings.append("image %s is not an image file (%s)" % (src, mime or "unknown type"))
                continue
            block["src"] = "data:%s;base64,%s" % (mime, base64.b64encode(path.read_bytes()).decode("ascii"))
    return warnings


TEXT_SKIP_KEYS = {"type", "tone", "level", "ordered", "src", "lang", "doc_type", "date", "id", "brand"}


def bilingual_gaps(model):
    """For a bilingual model: (half_filled, plain) lists of field paths.

    half_filled - an {vi, en} pair with one side missing or empty: the reader
                  sees a blank when switching language. Always a defect.
    plain       - a plain string where a pair was expected. Fine for numbers
                  and names that read the same in both languages; otherwise a
                  gap.
    """
    half, bare = [], []

    def visit(value, path):
        if is_dual(value):
            for code in LANG_KEYS:
                side = value.get(code)
                if side is None or str(side).strip() == "":
                    half.append("%s (%s empty)" % (path, code))
            return
        if isinstance(value, str):
            if value.strip():
                bare.append(path)
            return
        if isinstance(value, dict):
            for key, child in value.items():
                if key in TEXT_SKIP_KEYS:
                    continue
                if key == "text" and (value.get("type") or "").lower() == "code":
                    continue
                visit(child, "%s.%s" % (path, key) if path else key)
        elif isinstance(value, list):
            for index, child in enumerate(value):
                visit(child, "%s[%d]" % (path, index))

    visit(model, "")
    return half, bare


def palette_style(palette, theme):
    """Both modes are emitted as attribute rules.

    A template that ships its own light fallback puts it on html[data-theme=...],
    which outranks a bare :root — so writing the palette's chosen mode to :root
    would silently lose to the template. Attribute rules plus a :root fallback
    (for templates with no theme attribute at all) covers both cases.
    """
    if not palette:
        return ""
    modes = palette.get("modes") or {}
    if not modes:
        return '<style id="palette-override">:root{%s}</style>' % _decls(palette.get("vars"))
    initial = theme or palette.get("default_mode") or "dark"
    blocks = [":root{%s}" % _decls(modes.get(initial))]
    for mode in ("dark", "light"):
        if mode in modes:
            blocks.append('html[data-theme="%s"]{%s}' % (mode, _decls(modes[mode])))
    return '<style id="palette-override">%s</style>' % "".join(blocks)


def _decls(variables):
    return "".join("%s:%s;" % (k, v) for k, v in (variables or {}).items())


def inject_palette(document, style):
    if not style:
        return document
    if "</head>" in document:
        return document.replace("</head>", style + "\n</head>", 1)
    return style + "\n" + document


def load_palette(name, path):
    palettes = json.loads(Path(path).read_text(encoding="utf-8-sig")).get("palettes") or {}
    if name not in palettes:
        raise KeyError(
            "unknown palette %r; available: %s" % (name, ", ".join(sorted(palettes)))
        )
    return palettes[name]


def main(argv=None):
    parser = argparse.ArgumentParser(description="Render a document model into an HTML template.")
    parser.add_argument("--model", required=True, help="document model JSON")
    parser.add_argument("--template", default=str(DEFAULT_TEMPLATE),
                        help="template folder - the one the user chose, a bundled "
                             "one or their own; defaults to technext-shell")
    parser.add_argument("--out", required=True, help="output HTML path")
    parser.add_argument("--palette", default="", help="palette name from palettes.json")
    parser.add_argument("--palettes", default="", help="palettes.json path")
    parser.add_argument("--palette-file", default="",
                        help="a palette JSON file (from custom_palette.py) instead of a named palette")
    parser.add_argument("--theme", default="", help="initial mode: dark or light")
    parser.add_argument("--bilingual", choices=("auto", "true", "false"), default="auto",
                        help="show the language switch; auto detects it from the model")
    args = parser.parse_args(argv)

    model_path = Path(args.model)
    model = json.loads(model_path.read_text(encoding="utf-8-sig"))
    image_warnings = embed_images(model, model_path.resolve().parent)
    template_dir = Path(args.template).expanduser()
    is_default_template = template_dir.resolve() == DEFAULT_TEMPLATE.resolve()
    entry = find_entry(template_dir)
    document = entry.read_text(encoding="utf-8")
    document, adapt_notes = adapt_template(document)
    has_toc_slot = bool(re.search(r"\{\{\s*toc\s*\}\}", document))

    palette = None
    if args.palette and args.palette_file:
        print("error: pass either --palette or --palette-file, not both", file=sys.stderr)
        return 2
    if args.palette_file:
        palette_path = Path(args.palette_file).expanduser()
        if not palette_path.is_file():
            print("error: no palette file at %s" % palette_path, file=sys.stderr)
            return 2
        try:
            palette = json.loads(palette_path.read_text(encoding="utf-8-sig"))
        except json.JSONDecodeError as exc:
            print("error: %s is not valid JSON (%s)" % (palette_path, exc), file=sys.stderr)
            return 2
        if not palette.get("modes"):
            print("error: %s has no \"modes\" object" % palette_path, file=sys.stderr)
            return 2
    elif args.palette:
        palettes_path = Path(args.palettes).expanduser() if args.palettes else \
            Path(__file__).resolve().parent.parent / "assets" / "palettes.json"
        try:
            palette = load_palette(args.palette, palettes_path)
        except KeyError as exc:
            print("error: %s" % exc, file=sys.stderr)
            return 2
    else:
        # No palette asked for: fall back to the one the template is designed
        # around, so a bare --template still produces the intended look.
        manifest = template_dir / "manifest.json"
        default_name = ""
        if manifest.is_file():
            try:
                default_name = (json.loads(manifest.read_text(encoding="utf-8-sig")) or {}).get("default_palette") or ""
            except json.JSONDecodeError:
                default_name = ""
        if default_name:
            palettes_path = Path(args.palettes).expanduser() if args.palettes else \
                Path(__file__).resolve().parent.parent / "assets" / "palettes.json"
            try:
                palette = load_palette(default_name, palettes_path)
                args.palette = default_name
            except KeyError:
                print("warning: template default_palette %r is not in %s" % (default_name, palettes_path),
                      file=sys.stderr)

    lang = plain(model.get("lang")) or "vi"
    theme = args.theme or (palette or {}).get("default_mode") or "dark"
    bilingual = has_dual(model) if args.bilingual == "auto" else (args.bilingual == "true")
    sections = model.get("sections")
    # ids the template itself uses; a section must not take one of them
    reserved = template_ids(document)

    values = {
        "title": esc(plain(model.get("title"), lang)),
        "title_html": rt(model.get("title")),
        "subtitle": rt(model.get("subtitle")),
        "date": esc(plain(model.get("date"), lang)),
        "doc_type": esc(plain(model.get("doc_type"), lang)),
        # optional: the organisation this document belongs to. Absent means
        # the bar label disappears rather than showing a made-up name.
        "brand": rt(model.get("brand")),
        "lang": esc(lang),
        "theme": esc(theme),
        "bilingual": "true" if bilingual else "false",
        # no {{toc}} in the template: the contents box goes on top of the body,
        # so every document has a clickable index to its sections
        "body": ("" if has_toc_slot else render_toc_nav(sections, reserved, lang, bilingual))
                + render_sections(sections, reserved),
        "toc": render_toc(sections, reserved),
    }

    document = PLACEHOLDER_RE.sub(
        lambda m: values[m.group(1)] if m.group(1) in values else m.group(0), document
    )
    document = inject_blocks(document)
    document = inject_palette(document, palette_style(palette, theme))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(document, encoding="utf-8")

    leftover = sorted(set(PLACEHOLDER_RE.findall(document)))
    print("rendered %s" % out)
    print("template: %s (%s)%s" % (template_dir.name, entry.name,
                                   "  [default]" if is_default_template else ""))
    print("palette: %s" % (args.palette or (Path(args.palette_file).name if args.palette_file else "template default")))
    print("theme: %s | language: %s | bilingual: %s" % (theme, lang, "yes" if bilingual else "no"))
    print("sections: %d" % len(sections or []))
    if leftover:
        print("unfilled placeholders: %s" % ", ".join("{{%s}}" % p for p in leftover))
    for note in adapt_notes:
        print("note: %s" % note)
    if not has_toc_slot:
        print("note: template has no {{toc}} - a clickable contents box was added above the body")
    for warning in image_warnings:
        print("warning: %s" % warning)
    if bilingual and not has_dual(model):
        print("note: the switch is forced on, but no field has an en/vi pair yet")
    elif bilingual:
        half, bare = bilingual_gaps(model)
        if half:
            print("warning: %d bilingual field(s) have one language empty - the reader sees a blank "
                  "after switching: %s" % (len(half), ", ".join(half[:6]) + (" ..." if len(half) > 6 else "")))
        if bare:
            print("note: %d field(s) are plain text in a bilingual document (fine for numbers and names): %s"
                  % (len(bare), ", ".join(bare[:6]) + (" ..." if len(bare) > 6 else "")))
        if not half and not bare:
            print("note: language switch will show; every text field has both vi and en")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())'''

# ======================================================================
# embedded: scripts/import_doc.py
# ======================================================================
SOURCES['import_doc'] = r'''#!/usr/bin/env python3
"""Turn a source document into the model JSON (references/content-model.md).

    python scripts/import_doc.py notes.md   --out .doc-styler/model.json
    python scripts/import_doc.py report.docx --out .doc-styler/model.json
    python scripts/import_doc.py --outline .doc-styler/model.json

Markdown and plain text go through parse_markdown(), a line-for-line port of
parseMarkdown() in assets/editor/src/core.js - the node test suite checks the
two against the same fixture, so the editor and this script always agree.

A .docx is read with the standard library only (zipfile + ElementTree): it is
first written out as Markdown - headings from the Heading/Title styles, lists
from Word numbering, **bold**/*italic* runs, hyperlinks, tables, embedded
images as data: URIs - and then parsed exactly like a .md file.

The result is a starting point, not a verdict: print the outline, show it to
the user, and reshape the model with them (SKILL.md step 4).
"""

from __future__ import annotations

import argparse
import base64
import json
import mimetypes
import posixpath
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

# ------------------------------------------------------------ markdown ----

VI_CHARS_RE = re.compile(
    "[ăâêôơưđàáảãạằắẳẵặầấẩẫậèéẻẽẹềếểễệìíỉĩịòóỏõọồốổỗộờớởỡợùúủũụừứửữựỳýỷỹỵ]", re.IGNORECASE)
BULLET_RE = re.compile(r"^(\s*)[-*•+]\s+(.*)$")
ORDERED_RE = re.compile(r"^(\s*)(\d{1,3})[.)]\s+(.*)$")
HEADING_RE = re.compile(r"^\s*(#{1,6})\s+(.*?)\s*#*\s*$")
KV_RE = re.compile(r"^\s*([^:]{1,40}?)\s*:\s*(\S.*)$")
TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)+\|?\s*$")
IMAGE_RE = re.compile(r'^\s*!\[([^\]]*)\]\(([^)\s]+)(?:\s+"([^"]*)")?\)\s*$')
FENCE_RE = re.compile(r"^\s*```\s*([A-Za-z0-9_+.#-]*)\s*$")
FENCE_ANY_RE = re.compile(r"^\s*```")
FENCE_CLOSE_RE = re.compile(r"^\s*```\s*$")
HR_RE_1 = re.compile(r"^\s*([-*_])\s*\1\s*\1[\s\-*_]*$")
HR_RE_2 = re.compile(r"^\s*(-{3,}|\*{3,}|_{3,})\s*$")
QUOTE_RE = re.compile(r"^\s*>\s?")
DATE_KEY_RE = re.compile(r"^(ngày|date|ngay)\b", re.IGNORECASE)


def detect_lang(text):
    return "vi" if VI_CHARS_RE.search(text or "") else "en"


def detect_doc_type(title, body):
    t = str(title or "").strip()
    if not t:
        t = str(body or "")[:600]
    t = t.lower()
    if re.search("biên bản|meeting minutes|minutes of meeting", t):
        return "meeting-minutes"
    if re.search("đề xuất|proposal|báo giá|quotation", t):
        return "proposal"
    if re.search("hướng dẫn|how-to|how to|quy trình", t):
        return "how-to"
    if re.search("bản tin|newsletter", t):
        return "newsletter"
    if re.search("đặc tả|specification|technical spec", t):
        return "spec"
    if re.search("memo|ghi nhớ nội bộ", t):
        return "memo"
    return "report"


def looks_like_date(value):
    v = str(value).strip()
    return bool(re.match(r"^\d{1,4}[-/.]\d{1,2}[-/.]\d{1,4}$", v)
                or re.match(r"^\d{1,2}\s+tháng\s+\d{1,2},?\s*\d{4}$", v, re.IGNORECASE))


def split_row(line):
    s = line.strip()
    if s[:1] == "|":
        s = s[1:]
    if s[-1:] == "|":
        s = s[:-1]
    cells = re.split(r"(?<!\\)\|", s)
    return [c.replace("\\|", "|").strip() for c in cells]


def is_table_row(line):
    return line.count("|") >= 2


def indent_width(ws):
    return sum(4 if ch == "\t" else 1 for ch in ws)


def list_entry(line):
    o = ORDERED_RE.match(line)
    if o:
        return {"indent": indent_width(o.group(1)), "ordered": True, "text": o.group(3).strip()}
    b = BULLET_RE.match(line)
    if b:
        return {"indent": indent_width(b.group(1)), "ordered": False, "text": b.group(2).strip()}
    return None


def build_list(entries):
    root = {"indent": entries[0]["indent"], "items": []}
    stack = [root]
    for e in entries:
        while len(stack) > 1 and e["indent"] < stack[-1]["indent"]:
            stack.pop()
        top = stack[-1]
        if e["indent"] > top["indent"] and top["items"]:
            parent = top["items"][-1]
            if isinstance(parent, str):
                parent = {"text": parent, "items": []}
                top["items"][-1] = parent
            if e["ordered"]:
                parent["ordered"] = True
            child = {"indent": e["indent"], "items": parent["items"]}
            stack.append(child)
            top = child
        top["items"].append(e["text"])
    return root["items"]


def parse_markdown(text, title=None, doc_type=None):
    """Markdown / plain text -> model. Mirrors parseMarkdown() in core.js."""
    text = str(text or "")
    lines = re.sub(r"\r\n?", "\n", text).split("\n")
    model = {"title": "", "subtitle": "", "date": "", "doc_type": "",
             "lang": detect_lang(text), "sections": []}
    sections = []
    state = {"current": None}
    pending = []

    def target():
        if state["current"] is None:
            state["current"] = {"heading": "", "level": 2, "blocks": []}
            sections.append(state["current"])
        return state["current"]

    def flush_paragraph():
        joined = re.sub(r"\s+", " ", " ".join(pending)).strip()
        if joined:
            target()["blocks"].append({"type": "paragraph", "text": joined})
        pending.clear()

    i = 0
    while i < len(lines):
        line = lines[i]
        trimmed = line.strip()

        fence_open = FENCE_RE.match(line)
        if fence_open or FENCE_ANY_RE.match(line):
            flush_paragraph()
            fence = []
            i += 1
            while i < len(lines) and not FENCE_CLOSE_RE.match(lines[i]):
                fence.append(lines[i])
                i += 1
            if fence:
                block = {"type": "code", "text": "\n".join(fence)}
                if fence_open and fence_open.group(1):
                    block["lang"] = fence_open.group(1)
                target()["blocks"].append(block)
            i += 1
            continue
        if not trimmed:
            flush_paragraph()
            i += 1
            continue

        head = HEADING_RE.match(line)
        if head:
            flush_paragraph()
            level, heading = len(head.group(1)), head.group(2).strip()
            if level == 1 and not model["title"]:
                model["title"] = heading
            elif level <= 2:
                state["current"] = {"heading": heading, "level": 2, "blocks": []}
                sections.append(state["current"])
            else:
                target()["blocks"].append({"type": "heading", "text": heading, "level": min(level, 6)})
            i += 1
            continue
        if HR_RE_1.match(line) or HR_RE_2.match(trimmed):
            flush_paragraph()
            target()["blocks"].append({"type": "hr"})
            i += 1
            continue
        image = IMAGE_RE.match(line)
        if image:
            flush_paragraph()
            block = {"type": "image", "src": image.group(2), "alt": image.group(1).strip()}
            if image.group(3):
                block["caption"] = image.group(3)
            target()["blocks"].append(block)
            i += 1
            continue
        if QUOTE_RE.match(line):
            flush_paragraph()
            quoted = []
            while i < len(lines) and QUOTE_RE.match(lines[i]):
                quoted.append(QUOTE_RE.sub("", lines[i], count=1).strip())
                i += 1
            quote_text = " ".join(q for q in quoted if q).strip()
            if quote_text:
                target()["blocks"].append({"type": "quote", "text": quote_text})
            continue
        if is_table_row(line):
            start, rows = i, []
            while i < len(lines) and is_table_row(lines[i]):
                rows.append(lines[i])
                i += 1
            if len(rows) >= 2 and TABLE_SEP_RE.match(rows[1]):
                flush_paragraph()
                target()["blocks"].append({"type": "table", "headers": split_row(rows[0]),
                                           "rows": [split_row(r) for r in rows[2:]]})
            else:
                pending.extend(lines[start:i])
            continue
        first = list_entry(line)
        if first:
            flush_paragraph()
            entries = []
            while i < len(lines):
                e = list_entry(lines[i])
                if not e:
                    break
                # a top-level item of the other kind starts a new list
                if e["indent"] <= first["indent"] and e["ordered"] != first["ordered"]:
                    break
                entries.append(e)
                i += 1
            target()["blocks"].append({"type": "list", "ordered": first["ordered"], "items": build_list(entries)})
            continue
        if KV_RE.match(line) and len(trimmed) < 120:
            kv_lines = []
            while i < len(lines) and KV_RE.match(lines[i]) and len(lines[i].strip()) < 120:
                kv_lines.append(KV_RE.match(lines[i]))
                i += 1
            flush_paragraph()
            target()["blocks"].append({"type": "kv",
                                       "pairs": [[m.group(1).strip(), m.group(2).strip()] for m in kv_lines]})
            continue
        pending.append(trimmed)
        i += 1
    flush_paragraph()

    for section in sections:
        for block in section.get("blocks") or []:
            if block["type"] != "kv":
                continue
            for pair in block["pairs"]:
                if not model["date"] and DATE_KEY_RE.match(pair[0]) and looks_like_date(pair[1]):
                    model["date"] = pair[1]

    model["doc_type"] = detect_doc_type(model["title"], text)
    model["sections"] = [s for s in sections if s["heading"] or s["blocks"]]
    if title:
        model["title"] = title
    if doc_type:
        model["doc_type"] = doc_type
    return model


# ---------------------------------------------------------------- docx ----

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
A = "http://schemas.openxmlformats.org/drawingml/2006/main"
PKG_REL = "http://schemas.openxmlformats.org/package/2006/relationships"
WP = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"


def w(tag):
    return "{%s}%s" % (W, tag)


BOLD_HEADING_RE = re.compile(r"^\*\*(.+)\*\*$")
MD_SPECIAL_RE = re.compile(r"([\\`*_\[\]])")
LINE_START_RE = re.compile(r"^(\s*)(#|>|[-*+•]\s|\d{1,3}[.)]\s|!\[|```)")


def escape_line_start(text):
    """A body paragraph that happens to start like Markdown ("1. ", "# ", "- ")
    must stay a paragraph: escape the marker so the parser leaves it alone and
    the renderer shows it as typed."""
    m = LINE_START_RE.match(text)
    if not m:
        return text
    if m.group(2)[0].isdigit():
        return re.sub(r"^(\s*\d{1,3})([.)])", r"\1\\\2", text, count=1)
    return text[:m.start(2)] + "\\" + text[m.start(2):]


def md_escape(text):
    return MD_SPECIAL_RE.sub(r"\\\1", text)


def _on(el):
    """A w:b / w:i toggle: present and not switched off."""
    if el is None:
        return False
    return el.get(w("val"), "true").lower() not in ("0", "false", "off", "none")


def _wrap(text, bold, italic):
    if not text.strip() or not (bold or italic):
        return text
    lead = text[:len(text) - len(text.lstrip())]
    trail = text[len(text.rstrip()):]
    core = text.strip()
    mark = ("**" if bold else "") + ("*" if italic else "")
    return "%s%s%s%s%s" % (lead, mark, core, mark[::-1], trail)


class Docx:
    def __init__(self, path):
        self.zip = zipfile.ZipFile(path)
        self.rels = self._rels("word/_rels/document.xml.rels")
        self.styles = self._styles()
        self.numbering = self._numbering()
        self.warnings = []

    def _read(self, name):
        try:
            return self.zip.read(name)
        except KeyError:
            return None

    def _rels(self, name):
        data = self._read(name)
        out = {}
        if data:
            for rel in ET.fromstring(data).findall("{%s}Relationship" % PKG_REL):
                out[rel.get("Id")] = (rel.get("Target"), rel.get("TargetMode"))
        return out

    def _styles(self):
        """styleId -> lower-case name; also fills self.style_numbering with
        the numbering a style carries itself (styleId -> (numId, ilvl))."""
        data = self._read("word/styles.xml")
        out = {}
        self.style_numbering = {}
        if data:
            for style in ET.fromstring(data).findall(w("style")):
                sid = style.get(w("styleId"))
                name = style.find(w("name"))
                out[sid] = (name.get(w("val")) if name is not None else "").lower()
                num = style.find("%s/%s" % (w("pPr"), w("numPr")))
                if num is not None and num.find(w("numId")) is not None:
                    ilvl = num.find(w("ilvl"))
                    self.style_numbering[sid] = (num.find(w("numId")).get(w("val")),
                                                 ilvl.get(w("val")) if ilvl is not None else None)
        return out

    def _numbering(self):
        """numId -> {ilvl: ordered?}"""
        data = self._read("word/numbering.xml")
        if not data:
            return {}
        root = ET.fromstring(data)
        abstract = {}
        for an in root.findall(w("abstractNum")):
            levels = {}
            for lvl in an.findall(w("lvl")):
                fmt = lvl.find(w("numFmt"))
                value = fmt.get(w("val")) if fmt is not None else "bullet"
                levels[lvl.get(w("ilvl"))] = value not in ("bullet", "none")
            abstract[an.get(w("abstractNumId"))] = levels
        out = {}
        for num in root.findall(w("num")):
            ref = num.find(w("abstractNumId"))
            if ref is not None:
                out[num.get(w("numId"))] = abstract.get(ref.get(w("val")), {})
        return out

    # --- paragraph content ---

    def style_of(self, p):
        ppr = p.find(w("pPr"))
        sid = ""
        if ppr is not None and ppr.find(w("pStyle")) is not None:
            sid = ppr.find(w("pStyle")).get(w("val")) or ""
        return sid, self.styles.get(sid, sid.lower())

    def runs_text(self, parent):
        """Markdown for the runs under a paragraph or hyperlink, merging
        neighbouring runs that share formatting."""
        pieces = []  # (text, bold, italic)
        for child in parent:
            if child.tag == w("r"):
                rpr = child.find(w("rPr"))
                bold = _on(rpr.find(w("b"))) if rpr is not None else False
                italic = _on(rpr.find(w("i"))) if rpr is not None else False
                for node in child:
                    if node.tag == w("t"):
                        pieces.append((md_escape(node.text or ""), bold, italic))
                    elif node.tag == w("tab"):
                        pieces.append((" ", bold, italic))
                    elif node.tag in (w("br"), w("cr")):
                        pieces.append((" ", bold, italic))
            elif child.tag == w("hyperlink"):
                label = self.runs_text(child)
                target = self.rels.get(child.get("{%s}id" % R), (None, None))[0]
                anchor = child.get(w("anchor"))
                url = target or ("#" + anchor if anchor else "")
                pieces.append(("[%s](%s)" % (label, url.replace(" ", "%20")) if url and label.strip() else label,
                               False, False))
            elif child.tag in (w("ins"), w("smartTag"), w("sdt"), w("sdtContent"), w("fldSimple")):
                pieces.append((self.runs_text(child), False, False))
        merged = []
        for text, bold, italic in pieces:
            if merged and merged[-1][1] == bold and merged[-1][2] == italic:
                merged[-1] = (merged[-1][0] + text, bold, italic)
            else:
                merged.append((text, bold, italic))
        return "".join(_wrap(t, b, i) for t, b, i in merged)

    def images_in(self, p):
        out = []
        for blip in p.iter("{%s}blip" % A):
            rid = blip.get("{%s}embed" % R)
            target = self.rels.get(rid, (None, None))[0]
            if not target:
                continue
            name = posixpath.normpath(posixpath.join("word", target))
            data = self._read(name)
            if data is None:
                self.warnings.append("image %s is linked, not embedded - skipped" % target)
                continue
            mime = mimetypes.guess_type(name)[0] or "image/png"
            if not mime.startswith("image/") or mime in ("image/x-emf", "image/x-wmf", "image/emf", "image/wmf"):
                self.warnings.append("image %s is %s, which browsers cannot show - skipped" % (target, mime))
                continue
            alt = ""
            for doc_pr in p.iter("{%s}docPr" % WP):
                alt = doc_pr.get("descr") or doc_pr.get("title") or ""
                break
            out.append("![%s](data:%s;base64,%s)" % (alt.replace("]", ")").replace("\n", " "), mime,
                                                     base64.b64encode(data).decode("ascii")))
        return out

    def list_info(self, p, style_name):
        ppr = p.find(w("pPr"))
        num = ppr.find(w("numPr")) if ppr is not None else None
        if num is not None and num.find(w("numId")) is not None:
            num_id = num.find(w("numId")).get(w("val"))
            if num_id == "0":
                return None
            ilvl_el = num.find(w("ilvl"))
            ilvl = ilvl_el.get(w("val")) if ilvl_el is not None else "0"
            ordered = self.numbering.get(num_id, {}).get(ilvl, False)
            return int(ilvl), ordered
        # numbering that comes from the paragraph style (List Bullet, List Number 2 ...)
        depth = re.search(r"(\d)$", style_name)
        ilvl = int(depth.group(1)) - 1 if depth and style_name.startswith("list ") else 0
        sid = self.style_of(p)[0]
        if sid in self.style_numbering:
            num_id, style_ilvl = self.style_numbering[sid]
            level = style_ilvl if style_ilvl is not None else str(ilvl)
            if num_id != "0":
                return int(level), self.numbering.get(num_id, {}).get(level, style_name.startswith("list number"))
        if style_name.startswith("list number"):
            return ilvl, True
        if style_name.startswith("list bullet") or style_name == "list paragraph":
            return ilvl, False
        return None

    # --- document ---

    def to_markdown(self):
        body = ET.fromstring(self.zip.read("word/document.xml")).find(w("body"))
        out = []
        subtitle = ""
        prev_kind = None

        def emit(line, kind):
            nonlocal prev_kind
            # keep list items and Key: Value lines contiguous; everything
            # else is its own paragraph
            if out and not (kind == prev_kind and kind in ("list", "kv")):
                out.append("")
            out.append(line)
            prev_kind = kind

        for el in body:
            if el.tag == w("tbl"):
                rows = []
                for tr in el.findall(w("tr")):
                    cells = []
                    for tc in tr.findall(w("tc")):
                        text = " ".join(self.runs_text(p).strip() for p in tc.iter(w("p")))
                        cells.append(re.sub(r"\s+", " ", text).strip().replace("|", "\\|"))
                    rows.append(cells)
                if not rows:
                    continue
                width = max(len(r) for r in rows)
                rows = [r + [""] * (width - len(r)) for r in rows]
                if width < 2:
                    for r in rows:
                        if r[0]:
                            emit(r[0], "p")
                    continue
                lines = ["| " + " | ".join(rows[0]) + " |", "|" + "---|" * width]
                lines += ["| " + " | ".join(r) + " |" for r in rows[1:]]
                emit("\n".join(lines), "table")
                continue
            if el.tag != w("p"):
                continue

            sid, style = self.style_of(el)
            text = re.sub(r"[ \t]+", " ", self.runs_text(el)).strip()
            images = self.images_in(el)

            level = None
            m = re.match(r"^(?:heading|đề mục)\s*(\d)$", style) or re.match(r"^heading(\d)$", sid.lower())
            if m:
                level = int(m.group(1))
            if style == "title" or sid.lower() == "title":
                level = 1
            if (style == "subtitle" or sid.lower() == "subtitle") and text:
                subtitle = subtitle or text
                continue

            # a short paragraph that is bold from end to end, not a sentence and
            # not a list item, is a heading typed by hand ("**1. Thông tin**")
            if text and not level and not self.list_info(el, style) and BOLD_HEADING_RE.match(text):
                inner = BOLD_HEADING_RE.match(text).group(1).strip()
                if len(inner) <= 90 and not inner.endswith((",", ".", ":", ";")) and "**" not in inner:
                    emit("## " + inner, "h")
                    for image in images:
                        emit(image, "image")
                    continue
            if text:
                if level:
                    emit("#" * min(level, 6) + " " + text, "h")
                elif "quote" in style:
                    emit("> " + text, "quote")
                else:
                    info = self.list_info(el, style)
                    if info:
                        ilvl, ordered = info
                        emit("  " * ilvl + ("1. " if ordered else "- ") + text, "list")
                    else:
                        text = escape_line_start(text)
                        emit(text, "kv" if KV_RE.match(text) and len(text) < 120 else "p")
            for image in images:
                emit(image, "image")
        return "\n".join(out) + "\n", subtitle


def _bold_cell(cell):
    m = BOLD_HEADING_RE.match(cell or "")
    return m.group(1).strip() if m and "**" not in m.group(1) else None


def tables_to_kv(model):
    """A two-column Word table whose first column is bold throughout is a list
    of labelled values (Vị trí | SE Intern), not a data table: make it kv."""
    for section in model.get("sections") or []:
        for i, block in enumerate(section.get("blocks") or []):
            if block.get("type") != "table":
                continue
            rows = [block.get("headers") or []] + (block.get("rows") or [])
            if not rows or any(len(r) != 2 for r in rows):
                continue
            keys = [_bold_cell(r[0]) for r in rows]
            if all(keys):
                section["blocks"][i] = {"type": "kv", "pairs": [[k, r[1]] for k, r in zip(keys, rows)]}
    return model


def import_docx(path, title=None, doc_type=None):
    doc = Docx(path)
    markdown, subtitle = doc.to_markdown()
    model = tables_to_kv(parse_markdown(markdown, title=title, doc_type=doc_type))
    if subtitle and not model.get("subtitle"):
        model["subtitle"] = subtitle
    return model, doc.warnings


# ------------------------------------------------------------- outline ----

def _text(value):
    if isinstance(value, dict) and ("vi" in value or "en" in value):
        return str(value.get("vi") or value.get("en") or "")
    return "" if value is None else str(value)


def _count_items(items):
    n = 0
    for item in items or []:
        n += 1
        if isinstance(item, dict) and not ("vi" in item or "en" in item):
            n += _count_items(item.get("items"))
    return n


def describe(block):
    kind = (block.get("type") or "paragraph").lower()
    if kind == "list":
        nested = any(isinstance(i, dict) and "items" in i for i in block.get("items") or [])
        return "list(%s%d%s)" % ("ordered, " if block.get("ordered") else "",
                                 _count_items(block.get("items")), ", nested" if nested else "")
    if kind == "table":
        return "table(%d rows)" % len(block.get("rows") or [])
    if kind == "heading":
        return "heading(h%d)" % int(block.get("level", 3))
    if kind == "callout":
        return "callout(%s)" % block.get("tone", "info")
    if kind == "kv":
        return "kv(%d)" % len(block.get("pairs") or [])
    if kind == "code":
        return "code(%s)" % (block.get("lang") or "text")
    if kind == "image":
        src = str(block.get("src") or "")
        return "image(%s)" % ("embedded" if src.startswith("data:") else src or "no src")
    return kind


def outline(model):
    lines = []
    title = _text(model.get("title"))
    lines.append("title: %s" % (title or "(none)"))
    if model.get("subtitle"):
        lines.append("subtitle: %s" % _text(model.get("subtitle")))
    lines.append("doc_type: %s | lang: %s%s" % (model.get("doc_type") or "report", _text(model.get("lang")) or "vi",
                                                 " | date: %s" % _text(model["date"]) if model.get("date") else ""))
    sections = model.get("sections") or []
    width = min(max([len(_text(s.get("heading")) or "(no heading)") for s in sections] + [10]) + 4, 48)
    for n, section in enumerate(sections, 1):
        heading = _text(section.get("heading")) or "(no heading)"
        if len(heading) > width - 4:
            heading = heading[:width - 5] + "…"
        blocks = ", ".join(describe(b) for b in section.get("blocks") or []) or "(empty)"
        lines.append("%2d. %s %s %s" % (n, heading, "." * max(3, width - len(heading)), blocks))
    return "\n".join(lines)


# ---------------------------------------------------------------- main ----

def main(argv=None):
    parser = argparse.ArgumentParser(description="Turn a .md / .txt / .docx file into the document model.")
    parser.add_argument("source", nargs="?", help="source document (.md, .markdown, .txt, .docx)")
    parser.add_argument("--out", help="model JSON to write (default: .doc-styler/model.json next to the source)")
    parser.add_argument("--title", help="override the detected title")
    parser.add_argument("--doc-type", help="override the detected doc_type")
    parser.add_argument("--outline", metavar="MODEL", help="only print the outline of an existing model JSON")
    args = parser.parse_args(argv)

    if args.outline:
        model = json.loads(Path(args.outline).read_text(encoding="utf-8-sig"))
        print(outline(model))
        return 0
    if not args.source:
        parser.error("a source document is required (or --outline MODEL)")

    source = Path(args.source).expanduser()
    if not source.is_file():
        print("error: not a file: %s" % source, file=sys.stderr)
        return 2
    suffix = source.suffix.lower()
    warnings = []
    if suffix == ".docx":
        try:
            model, warnings = import_docx(source, args.title, args.doc_type)
        except (zipfile.BadZipFile, KeyError, ET.ParseError) as exc:
            print("error: %s is not a readable .docx (%s)" % (source, exc), file=sys.stderr)
            return 2
    elif suffix in (".md", ".markdown", ".txt", ".text", ""):
        model = parse_markdown(source.read_text(encoding="utf-8-sig"), args.title, args.doc_type)
    elif suffix == ".doc":
        print("error: .doc (Word 97-2003) is not supported - save it as .docx first", file=sys.stderr)
        return 2
    else:
        print("error: unsupported file type %s - use .md, .txt or .docx; for .html use the editor "
              "(assets/editor/doc-styler-editor.html), for PDF extract the text first" % suffix, file=sys.stderr)
        return 2

    out = Path(args.out) if args.out else source.parent / ".doc-styler" / "model.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(model, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("wrote %s" % out)
    for warning in warnings:
        print("warning: %s" % warning)
    print()
    print(outline(model))
    if not model.get("sections"):
        print("\nnote: no content found - is the source empty, or a scanned document with no text layer?")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

# ======================================================================
# embedded: scripts/validate_output.py
# ======================================================================
SOURCES['validate_output'] = r'''#!/usr/bin/env python3
"""Mechanical checks on a rendered HTML document before handing it to the user.

    python scripts/validate_output.py out.html --require-palette [--model m.json]

Errors (exit 1): unfilled placeholders, resources loaded over the network,
missing body, duplicate ids, contents links that land nowhere, a bilingual
pair with one side empty. Warnings: plain text inside a bilingual document
(pass --model to see which fields), missing lang attribute.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_doc import bilingual_gaps  # noqa: E402

LEFT_OVER_RE = re.compile(r"\{\{\s*[A-Za-z0-9_.-]+\s*\}\}")
# Things the browser fetches. A plain <a href="https://..."> is a link the
# reader may follow, not a resource the page needs, so it is not counted.
EXTERNAL_RES = (
    re.compile(r"""<(?:img|script|iframe|source|video|audio|embed|track|input)\b[^>]*\ssrc\s*=\s*["']?(?:https?:)?//""", re.I),
    re.compile(r"""<link\b[^>]*\shref\s*=\s*["']?(?:https?:)?//""", re.I),
    re.compile(r"""url\(\s*["']?(?:https?:)?//""", re.I),
    re.compile(r"""@import\s+(?:url\()?\s*["']?(?:https?:)?//""", re.I),
    re.compile(r"""<object\b[^>]*\sdata\s*=\s*["']?(?:https?:)?//""", re.I),
)
REQUIRED_BLOCKS = ('<section class="doc-section"',)
ID_RE = re.compile(r"""\sid\s*=\s*["']([^"']+)["']""")
ANCHOR_RE = re.compile(r"""\shref\s*=\s*["']#([^"']+)["']""")
LONE_VI_RE = re.compile(r'<span class="t-vi">((?:(?!</span>).)*)</span>(?!<span class="t-en">)', re.S)
LONE_EN_RE = re.compile(r'(?<!</span>)<span class="t-en">((?:(?!</span>).)*)</span>', re.S)
EMPTY_PAIR_RE = re.compile(r'<span class="t-(vi|en)">\s*</span>')


def _strip_scripts(text):
    return re.sub(r"<script\b.*?</script>", "", text, flags=re.S | re.I)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Validate a rendered HTML document.")
    parser.add_argument("file", help="rendered HTML file")
    parser.add_argument("--require-palette", action="store_true", help="fail if no palette override is present")
    parser.add_argument("--min-sections", type=int, default=1)
    parser.add_argument("--model", help="the model JSON it was rendered from - names the exact fields "
                                        "that break the bilingual rule")
    args = parser.parse_args(argv)

    path = Path(args.file)
    if not path.is_file():
        print("error: not a file: %s" % path, file=sys.stderr)
        return 2
    text = path.read_text(encoding="utf-8", errors="replace")
    markup = _strip_scripts(text)

    errors = []
    warnings = []

    if "<!DOCTYPE" not in text.upper():
        errors.append("missing <!DOCTYPE html>")
    leftover = sorted(set(LEFT_OVER_RE.findall(text)))
    if leftover:
        errors.append("unfilled placeholders: " + ", ".join(leftover))
    external = sum(len(r.findall(markup)) for r in EXTERNAL_RES)
    if external:
        errors.append("external http(s) resource(s) found: %d - document will not render offline" % external)
    sections = text.count('<section class="doc-section"')
    # --min-sections 0 means the document is legitimately blank, so a missing
    # body is the expected result rather than a substitution failure
    if args.min_sections > 0 and not any(block in text for block in REQUIRED_BLOCKS):
        errors.append('no <section class="doc-section"> found; body was probably not substituted')
    if sections < args.min_sections:
        errors.append("expected at least %d section(s), found %d" % (args.min_sections, sections))
    if args.require_palette and 'id="palette-override"' not in text:
        errors.append("palette override requested but not present in output")
    if text.count("<html") and "lang=" not in text.split(">", 2)[1]:
        warnings.append("<html> has no lang attribute")

    # every id once, every in-page link lands somewhere
    ids = ID_RE.findall(markup)
    dupes = sorted(k for k, n in Counter(ids).items() if n > 1)
    if dupes:
        errors.append("duplicate id(s): %s - contents links jump to the first one only" % ", ".join(dupes))
    broken = sorted(set(a for a in ANCHOR_RE.findall(markup) if a not in set(ids)))
    if broken:
        errors.append("link(s) to missing section(s): %s" % ", ".join("#" + b for b in broken))

    # the contents: every headed section is reachable from a link
    headed = re.findall(r'<section class="doc-section" id="([^"]+)">\s*<h[1-6]', markup)
    linked = set(ANCHOR_RE.findall(markup))
    unlisted = [h for h in headed if h not in linked]
    if unlisted:
        errors.append("%d section(s) missing from the contents: %s"
                      % (len(unlisted), ", ".join("#" + u for u in unlisted[:8])))

    # both languages or neither
    bilingual = 'data-bilingual="true"' in text.split(">", 2)[1] if "<html" in text else False
    if bilingual:
        lone_vi = len(LONE_VI_RE.findall(markup))
        lone_en = len(LONE_EN_RE.findall(markup))
        empty = len(EMPTY_PAIR_RE.findall(markup))
        if lone_vi or lone_en or empty:
            errors.append("bilingual text incomplete: %d Vietnamese-only, %d English-only, %d empty side(s) - "
                          "the reader sees a blank after switching language%s"
                          % (lone_vi, lone_en, empty, "" if args.model else " (pass --model to list the fields)"))
    if args.model:
        model = json.loads(Path(args.model).read_text(encoding="utf-8-sig"))
        half, bare = bilingual_gaps(model)
        if bilingual and half:
            errors.append("half-filled field(s): %s" % ", ".join(half[:12]) + (" ..." if len(half) > 12 else ""))
        if bilingual and bare:
            warnings.append("%d plain-text field(s) in a bilingual document - fine for numbers and names, "
                            "otherwise translate them: %s" % (len(bare), ", ".join(bare[:12]) + (" ..." if len(bare) > 12 else "")))

    print("%s: %d section(s), %d byte(s)" % (path.name, sections, len(text.encode("utf-8"))))
    for warning in warnings:
        print("warning: %s" % warning)
    for error in errors:
        print("error: %s" % error)
    print("result: %s" % ("FAIL" if errors else "PASS"))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

# ======================================================================
# embedded: scripts/custom_palette.py
# ======================================================================
SOURCES['custom_palette'] = r'''#!/usr/bin/env python3
"""Turn a couple of colour choices into a palette render_doc.py can use.

The fallback path when none of the templates suit the document: the user names
one or two colours, this derives a complete, legible set for both modes, and
the result is a palette file:

    python scripts/custom_palette.py --primary "#8C4A2F" --mode light --out my-palette.json
    python scripts/render_doc.py --model m.json --template <dir> \
        --palette-file my-palette.json --out out.html

Any value the user does not give is derived. The derivation is the same one the
editor uses (assets/editor/src/core.js), so a colour set made here and one made
by clicking in the editor produce identical CSS.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

VARS = ("--brand-primary", "--brand-accent", "--brand-ink", "--doc-bg", "--doc-surface")
HEX_RE = re.compile(r"^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


def hex_to_rgb(value):
    m = HEX_RE.match(str(value or "").strip())
    if not m:
        raise ValueError("%r is not a hex colour like #0e7c8c" % value)
    h = m.group(1)
    if len(h) == 3:
        h = h[0] * 2 + h[1] * 2 + h[2] * 2
    return [int(h[i:i + 2], 16) for i in (0, 2, 4)]


def rgb_to_hex(rgb):
    out = ""
    for v in rgb:
        n = max(0, min(255, round(v)))
        out += "%02x" % n
    return "#" + out


def rgb_to_hsl(rgb):
    r, g, b = (v / 255 for v in rgb)
    high, low = max(r, g, b), min(r, g, b)
    light = (high + low) / 2
    if high == low:
        return [0.0, 0.0, light * 100]
    delta = high - low
    sat = delta / (2 - high - low) if light > 0.5 else delta / (high + low)
    if high == r:
        hue = (g - b) / delta + (6 if g < b else 0)
    elif high == g:
        hue = (b - r) / delta + 2
    else:
        hue = (r - g) / delta + 4
    return [hue * 60, sat * 100, light * 100]


def hsl_to_rgb(hsl):
    hue = ((hsl[0] % 360) + 360) % 360 / 360
    sat, light = hsl[1] / 100, hsl[2] / 100

    def channel(p, q, t):
        if t < 0:
            t += 1
        if t > 1:
            t -= 1
        if t < 1 / 6:
            return p + (q - p) * 6 * t
        if t < 1 / 2:
            return q
        if t < 2 / 3:
            return p + (q - p) * (2 / 3 - t) * 6
        return p

    if sat == 0:
        return [light * 255] * 3
    q = light * (1 + sat) if light < 0.5 else light + sat - light * sat
    p = 2 * light - q
    return [channel(p, q, hue + 1 / 3) * 255, channel(p, q, hue) * 255, channel(p, q, hue - 1 / 3) * 255]


def set_lightness(colour, lightness, saturation_scale=None):
    hsl = rgb_to_hsl(hex_to_rgb(colour))
    hsl[2] = lightness
    if saturation_scale is not None:
        hsl[1] = min(100, hsl[1] * saturation_scale)
    return rgb_to_hex(hsl_to_rgb(hsl))


def derive_counterpart(variables, from_mode):
    """The opposite of the mode the user just picked, so the reader's theme
    toggle always lands on something readable."""
    primary = variables["--brand-primary"]
    accent = variables["--brand-accent"]
    dark = from_mode == "dark"
    return {
        "--brand-primary": set_lightness(primary, 32 if dark else 62),
        "--brand-accent": set_lightness(accent, 40 if dark else 66),
        "--brand-ink": set_lightness(primary, 14, 0.55) if dark else "#e8eef6",
        "--doc-bg": set_lightness(primary, 95, 0.35) if dark else set_lightness(primary, 8, 0.6),
        "--doc-surface": "#ffffff" if dark else set_lightness(primary, 14, 0.6),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description="Build a palette file from a few colours.")
    parser.add_argument("--primary", required=True, help="brand colour the document leads with")
    parser.add_argument("--accent", default="", help="secondary colour; derived from --primary if omitted")
    parser.add_argument("--ink", default="", help="body text colour; derived if omitted")
    parser.add_argument("--bg", default="", help="page background; derived if omitted")
    parser.add_argument("--surface", default="", help="card/panel background; derived if omitted")
    parser.add_argument("--mode", choices=("dark", "light"), default="light",
                        help="which mode the colours you gave describe (default: light)")
    parser.add_argument("--name", default="", help="label written into the file")
    parser.add_argument("--out", required=True, help="palette JSON to write")
    args = parser.parse_args(argv)

    try:
        primary = rgb_to_hex(hex_to_rgb(args.primary))
        accent = rgb_to_hex(hex_to_rgb(args.accent)) if args.accent else set_lightness(primary, 42)
    except ValueError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2

    dark = args.mode == "dark"
    chosen = {
        "--brand-primary": primary,
        "--brand-accent": accent,
        "--brand-ink": rgb_to_hex(hex_to_rgb(args.ink)) if args.ink else (
            "#e8eef6" if dark else set_lightness(primary, 14, 0.55)),
        "--doc-bg": rgb_to_hex(hex_to_rgb(args.bg)) if args.bg else (
            set_lightness(primary, 8, 0.6) if dark else set_lightness(primary, 95, 0.35)),
        "--doc-surface": rgb_to_hex(hex_to_rgb(args.surface)) if args.surface else (
            set_lightness(primary, 14, 0.6) if dark else "#ffffff"),
    }
    other = "light" if dark else "dark"
    palette = {
        "label": args.name or ("Custom " + args.mode),
        "default_mode": args.mode,
        "modes": {args.mode: chosen, other: derive_counterpart(chosen, args.mode)},
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(palette, ensure_ascii=False, indent=2) + chr(10), encoding="utf-8")

    print("wrote %s" % out)
    print("mode given: %s | derived: %s" % (args.mode, other))
    for mode in ("dark", "light"):
        print("  %-5s %s" % (mode, "  ".join("%s=%s" % (k, v) for k, v in palette["modes"][mode].items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

# ======================================================================
# embedded: scripts/preview_sheet.py
# ======================================================================
SOURCES['preview_sheet'] = r'''#!/usr/bin/env python3
"""Render one document through every template, side by side, so a template can
be chosen by looking rather than by reading manifests.

    python scripts/preview_sheet.py --model model.json \
        --templates assets/templates --out preview --palette slate

Writes preview-<template>.html per template plus an index.html that shows them
all as scaled thumbnails with a link to open each at full size. Add
--palette-matrix to give every card a row of palette buttons that repaint its
thumbnail in place, which is how a template-plus-colour is picked.

The index is self-contained (thumbnails are embedded, not loaded), so it opens
straight from file:// with no server and no network.
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
from contextlib import redirect_stdout
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import render_doc as R  # noqa: E402

BODY_RE = re.compile(r"\{\{\s*body\s*\}\}")
BRAND_VARS = ("--brand-primary", "--brand-accent", "--brand-ink", "--doc-bg", "--doc-surface")


def find_templates(root):
    found = []
    for folder in sorted(p for p in Path(root).iterdir() if p.is_dir()):
        try:
            entry = R.find_entry(folder)
        except FileNotFoundError:
            continue
        manifest = {}
        mpath = folder / "manifest.json"
        if mpath.is_file():
            try:
                manifest = json.loads(mpath.read_text(encoding="utf-8-sig"))
            except json.JSONDecodeError:
                manifest = {}
        found.append({
            "id": manifest.get("id") or folder.name,
            "label": manifest.get("label") or folder.name,
            "use_when": manifest.get("use_when") or "",
            "default_palette": manifest.get("default_palette") or "",
            "folder": folder,
            "entry": entry,
        })
    return found


def js_json(value):
    text = json.dumps(value, ensure_ascii=False, indent=1)
    return text.replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")

INDEX = """<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Chọn template - __TITLE__</title>
<style>
:root{--bg:#0b0f14;--surf:#121820;--surf2:#172029;--line:#242f3b;--ink:#e7edf5;--mut:#8b99aa;--acc:#37d3c3;--err:#f2757a}
*{box-sizing:border-box}
body{margin:0;padding:34px 26px 60px;background:var(--bg);color:var(--ink);
 font:14px/1.55 system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:1500px;margin:0 auto}
.eyebrow{font:700 .7rem/1 system-ui;letter-spacing:.14em;text-transform:uppercase;color:var(--acc)}
h1{font-size:1.5rem;margin:10px 0 8px;letter-spacing:-.01em}
.meta{color:var(--mut);font-size:.85rem;margin:0 0 26px}
.meta code{color:#9fd3ff}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(380px,1fr));gap:18px}
.card{background:var(--surf);border:1px solid var(--line);border-radius:14px;overflow:hidden}
.card .th{height:340px;overflow:hidden;position:relative;background:#fff;border-bottom:1px solid var(--line)}
.card .th iframe{width:1000px;height:1400px;border:0;transform-origin:top left;position:absolute;top:0;left:0;pointer-events:none}
.card .bd{padding:13px 15px 15px}
.card h2{margin:0 0 4px;font-size:1rem}
.card .use{color:var(--mut);font-size:.79rem;margin:0 0 10px}
.chips{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 11px}
.chip{font:600 .67rem/1 ui-monospace,Consolas,monospace;text-transform:uppercase;letter-spacing:.05em;
 background:var(--surf2);border:1px solid var(--line);border-radius:999px;padding:4px 8px;color:var(--mut)}
.chip.ok{color:var(--acc);border-color:color-mix(in oklab,var(--acc) 45%,var(--line))}
.chip.no{color:var(--err);border-color:color-mix(in oklab,var(--err) 45%,var(--line))}
.picks{display:flex;gap:5px;flex-wrap:wrap;margin:0 0 12px}
.pick{font:600 .68rem/1 system-ui;letter-spacing:.03em;background:var(--surf2);border:1px solid var(--line);
 border-radius:8px;padding:5px 9px;color:var(--mut);cursor:pointer}
.pick:hover{border-color:var(--acc);color:var(--acc)}
.pick.on{background:var(--acc);border-color:var(--acc);color:#06231f}
.open{display:inline-block;text-decoration:none;color:var(--ink);background:var(--surf2);
 border:1px solid var(--line);border-radius:9px;padding:7px 12px;font-size:.82rem;font-weight:600}
.open:hover{border-color:var(--acc);color:var(--acc)}
.foot{margin-top:26px;color:var(--mut);font-size:.78rem}
</style>
</head>
<body>
<div class="wrap">
  <div class="eyebrow">doc-template-styler - chọn template</div>
  <h1>__TITLE__</h1>
  <p class="meta">__SUBTITLE__<br>__N__ template, __VARIANTS__. Xem trước bằng cùng một tài liệu để so sánh bố cục thay vì đọc manifest.</p>
  <div class="grid" id="grid"></div>
  <p class="foot">Mỗi ô là bản render thật của cùng một model. Bấm các nút màu để đổi palette ngay trên thumbnail; bấm "Mở file" để xem toàn trang (bản đó có sẵn nút đổi sáng/tối và EN/VI).</p>
</div>
<script>window.PREVIEWS = __DATA__;</script>
<script>
(function () {
  var host = document.getElementById('grid');
  window.PREVIEWS.forEach(function (t) {
    var frame = document.createElement('iframe');
    frame.setAttribute('title', t.label);
    var th = document.createElement('div');
    th.className = 'th';
    th.appendChild(frame);
    var card = document.createElement('div');
    card.className = 'card';
    var bd = document.createElement('div');
    bd.className = 'bd';
    var h2 = document.createElement('h2'); h2.textContent = t.label;
    var use = document.createElement('p'); use.className = 'use'; use.textContent = t.use_when || '';
    var chipRow = document.createElement('div'); chipRow.className = 'chips';
    (t.chips || []).forEach(function (c) {
      var s = document.createElement('span');
      s.className = 'chip ' + c.cls;
      s.textContent = c.text;
      chipRow.appendChild(s);
    });
    var open = document.createElement('a');
    open.className = 'open'; open.target = '_blank'; open.textContent = 'Mở file';
    var pvRow = document.createElement('div'); pvRow.className = 'picks';
    var buttons = [];
    function pick(i) {
      var v = t.variants[i];
      frame.srcdoc = v.html;
      open.href = v.file;
      buttons.forEach(function (b, j) { b.className = 'pick' + (j === i ? ' on' : ''); });
    }
    t.variants.forEach(function (v, i) {
      var b = document.createElement('button');
      b.type = 'button';
      b.className = 'pick';
      b.textContent = v.label;
      b.title = v.theme;
      b.addEventListener('click', function () { pick(i); });
      buttons.push(b); pvRow.appendChild(b);
    });
    bd.appendChild(h2); bd.appendChild(use); bd.appendChild(chipRow); bd.appendChild(pvRow); bd.appendChild(open);
    card.appendChild(th); card.appendChild(bd);
    host.appendChild(card);
    pick(0);
    requestAnimationFrame(function () {
      frame.style.transform = 'scale(' + (th.clientWidth / 1000) + ')';
    });
  });
})();
</script>
</body>
</html>
"""

def load_palettes(path):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8-sig")).get("palettes") or {}
    except (OSError, json.JSONDecodeError):
        return {}


def main(argv=None):
    parser = argparse.ArgumentParser(description="Render one model through every template for comparison.")
    parser.add_argument("--model", required=True)
    parser.add_argument("--templates", required=True, help="folder holding one directory per template")
    parser.add_argument("--out", required=True, help="output folder for the previews and index.html")
    parser.add_argument("--palette", default="", help="one palette applied to every template")
    parser.add_argument("--palette-file", default="")
    parser.add_argument("--palettes", default="", help="palettes.json path")
    parser.add_argument("--palette-matrix", default="",
                        help="comma-separated palette names, or 'all': every card gets one button per palette")
    parser.add_argument("--mode", choices=("auto", "dark", "light"), default="auto")
    args = parser.parse_args(argv)

    out = Path(args.out).expanduser()
    out.mkdir(parents=True, exist_ok=True)

    model_path = Path(args.model).expanduser()
    model = json.loads(model_path.read_text(encoding="utf-8-sig"))
    lang = R.plain(model.get("lang")) or "vi"

    palettes_path = Path(args.palettes).expanduser() if args.palettes else \
        Path(__file__).resolve().parent.parent / "assets" / "palettes.json"
    all_palettes = load_palettes(palettes_path)

    single = None
    palette_name = "template default"
    if args.palette_file:
        single = json.loads(Path(args.palette_file).expanduser().read_text(encoding="utf-8-sig"))
        palette_name = Path(args.palette_file).name
    elif args.palette:
        single = R.load_palette(args.palette, palettes_path)
        palette_name = args.palette

    matrix = []
    if args.palette_matrix:
        wanted = args.palette_matrix.strip()
        matrix = sorted(all_palettes) if wanted.lower() == "all" else \
            [p.strip() for p in wanted.split(",") if p.strip()]
        if not matrix:
            print("error: --palette-matrix selected no palette", file=sys.stderr)
            return 2
        unknown = [p for p in matrix if p not in all_palettes]
        if unknown:
            print("error: unknown palette(s): %s; available: %s"
                  % (", ".join(unknown), ", ".join(sorted(all_palettes))), file=sys.stderr)
            return 2

    mode = args.mode
    if mode == "auto":
        mode = (single or {}).get("default_mode") or "dark"

    def render(target, cli):
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            code = R.main(cli)
        lines = buffer.getvalue().strip().splitlines()
        return code, (lines[-1] if lines else "")

    templates = find_templates(args.templates)
    if not templates:
        print("error: no template found in %s" % args.templates, file=sys.stderr)
        return 2

    cards = []
    for tpl in templates:
        entry_text = tpl["entry"].read_text(encoding="utf-8")
        placeholders = sorted(set(R.PLACEHOLDER_RE.findall(entry_text)))
        chips = []
        if not BODY_RE.search(entry_text):
            chips.append({"text": "khong co {{body}}", "cls": "no"})
        if any(v not in entry_text for v in BRAND_VARS):
            chips.append({"text": "mau co dinh", "cls": "no"})
        if not chips:
            chips.append({"text": "san sang", "cls": "ok"})
        chips.append({"text": str(len(placeholders)) + " placeholder", "cls": ""})

        specs = []
        if matrix:
            names = list(matrix)
            default_name = tpl["default_palette"]
            if default_name and default_name in names:
                # the template's own palette goes first, so the thumbnail
                # opens on the look the template was designed around
                names = [default_name] + [n for n in names if n != default_name]
            elif default_name:
                names = [default_name] + names
            for name in names:
                theme = args.mode if args.mode != "auto" else (all_palettes[name].get("default_mode") or "dark")
                label = name + ("  *" if name == tpl["default_palette"] else "")
                specs.append((label, "preview-%s-%s.html" % (tpl["id"], name), theme, ["--palette", name]))
        else:
            extra = []
            if args.palette_file:
                extra = ["--palette-file", args.palette_file]
            elif args.palette:
                extra = ["--palette", args.palette]
            specs.append((palette_name, "preview-%s.html" % tpl["id"], mode, extra))

        variants = []
        for label, filename, theme, extra in specs:
            target = out / filename
            cli = ["--model", str(model_path), "--template", str(tpl["folder"]),
                   "--out", str(target), "--theme", theme] + extra
            if args.palettes:
                cli += ["--palettes", args.palettes]
            code, _note = render(target, cli)
            if code != 0:
                print("error: rendering %s failed" % tpl["id"], file=sys.stderr)
                return code
            variants.append({
                "label": label, "theme": theme, "file": filename,
                "html": target.read_text(encoding="utf-8"),
            })
        if len(variants) > 1:
            chips.append({"text": str(len(variants)) + " mau", "cls": ""})
        cards.append({"id": tpl["id"], "label": tpl["label"], "use_when": tpl["use_when"],
                      "chips": chips, "variants": variants})
        print("  %-18s -> %d variant(s)" % (tpl["id"], len(variants)))

    title = R.plain(model.get("title"), lang) or "Tai lieu"
    if matrix:
        if args.mode == "auto":
            note = ("mỗi card một nút cho từng palette, chế độ lấy theo từng palette"
                    " (* = palette mặc định của template)")
        else:
            note = ("mỗi card một nút cho từng palette, chế độ <code>%s</code>"
                    " (* = palette mặc định của template)" % R.esc(mode))
    else:
        note = "palette <code>%s</code>, chế độ <code>%s</code>" % (R.esc(palette_name), R.esc(mode))
    page = (INDEX
            .replace("__TITLE__", R.esc(title))
            .replace("__SUBTITLE__", R.esc(R.plain(model.get("subtitle"), lang) or model_path.name))
            .replace("__N__", str(len(cards)))
            .replace("__VARIANTS__", note)
            .replace("__DATA__", js_json(cards)))
    index_path = out / "index.html"
    index_path.write_text(page, encoding="utf-8")

    print("\nwrote %s" % index_path)
    print("open it, then say which template + colour to use (or none, and give your own colour)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

# ======================================================================
# embedded: scripts/scan_templates.py
# ======================================================================
SOURCES['scan_templates'] = r'''#!/usr/bin/env python3
"""Scan a folder of HTML templates and emit a machine-readable registry.

A template is any subfolder containing at least one .html file. If the folder
has a manifest.json it is used; otherwise metadata is inferred from the markup
(placeholders, CSS custom properties).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REQUIRED_PLACEHOLDERS = ("title", "body")
REQUIRED_CSS_VARS = ("--brand-primary", "--brand-accent", "--brand-ink", "--doc-bg", "--doc-surface")
PLACEHOLDER_RE = re.compile(r"\{\{\s*([A-Za-z0-9_.-]+)\s*\}\}")
CSS_VAR_RE = re.compile(r"(--[A-Za-z0-9-]+)\s*:\s*([^;{}]+);")
TEXT_SUFFIXES = {".html", ".htm", ".css"}
PREFERRED_ENTRIES = ("template.html", "index.html", "template.htm", "index.htm")


def humanize(name):
    return name.replace("_", "-").strip("-").replace("-", " ").title()


def find_entry(folder, manifest):
    entry = manifest.get("entry")
    if entry:
        candidate = folder / entry
        return candidate if candidate.is_file() else None
    for name in PREFERRED_ENTRIES:
        candidate = folder / name
        if candidate.is_file():
            return candidate
    html_files = sorted(p for p in folder.rglob("*.htm*") if p.is_file())
    return html_files[0] if html_files else None


def read_manifest(folder):
    path = folder / "manifest.json"
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError as exc:
        return {"_manifest_error": str(exc)}


def scan_template(folder):
    manifest = read_manifest(folder)
    entry = find_entry(folder, manifest)

    chunks = []
    if entry:
        chunks.append(entry.read_text(encoding="utf-8", errors="replace"))
    for css in sorted(folder.rglob("*.css")):
        chunks.append(css.read_text(encoding="utf-8", errors="replace"))
    if entry:
        for other in sorted(folder.rglob("*.htm*")):
            if other != entry:
                chunks.append(other.read_text(encoding="utf-8", errors="replace"))
    text = "\n".join(chunks)

    placeholders = sorted(set(PLACEHOLDER_RE.findall(text)))
    css_vars = {}
    for name, value in CSS_VAR_RE.findall(text):
        css_vars.setdefault(name, value.strip())

    issues = []
    if manifest.get("_manifest_error"):
        issues.append("manifest.json is not valid JSON: " + manifest["_manifest_error"])
    if entry is None:
        issues.append("no .html entry file found")
    missing_ph = [p for p in REQUIRED_PLACEHOLDERS if p not in placeholders]
    if missing_ph:
        issues.append("missing required placeholder(s): " + ", ".join("{{%s}}" % p for p in missing_ph))
    missing_vars = [v for v in REQUIRED_CSS_VARS if v not in css_vars]
    if missing_vars:
        issues.append("missing colour variable(s): " + ", ".join(missing_vars))
    if re.search(r'(?:src|href)\s*=\s*["\']https?://', text, re.IGNORECASE):
        issues.append("loads an external http(s) resource (breaks offline file:// use)")

    folder_name = folder.name
    return {
        "id": manifest.get("id") or folder_name,
        "label": manifest.get("label") or humanize(folder_name),
        "description": manifest.get("description") or "",
        "use_when": manifest.get("use_when") or "",
        "doc_types": manifest.get("doc_types") or [],
        "default_palette": manifest.get("default_palette") or "",
        "entry": entry.relative_to(folder).as_posix() if entry else "",
        "placeholders": placeholders,
        "css_vars": css_vars,
        "path": str(folder),
        "issues": issues,
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description="Scan HTML templates into a registry.")
    parser.add_argument("templates_dir", help="folder holding one subfolder per template")
    parser.add_argument("--out", help="write the registry JSON here instead of stdout")
    args = parser.parse_args(argv)

    root = Path(args.templates_dir).expanduser()
    if not root.is_dir():
        print("error: not a directory: %s" % root, file=sys.stderr)
        return 2

    templates = []
    for child in sorted(p for p in root.iterdir() if p.is_dir()):
        if any(f.suffix.lower() in {".html", ".htm"} for f in child.rglob("*")):
            templates.append(scan_template(child))

    registry = {"templates_dir": str(root), "templates": templates}
    payload = json.dumps(registry, indent=2, ensure_ascii=False)

    if args.out:
        Path(args.out).write_text(payload + "\n", encoding="utf-8")
        print("wrote %d template(s) to %s" % (len(templates), args.out))
    else:
        print(payload)

    blocked = [t["id"] for t in templates if t["issues"]]
    if blocked:
        print("templates with issues: %s" % ", ".join(blocked), file=sys.stderr)
    if not templates:
        print("warning: no templates found in %s" % root, file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())'''

# ======================================================================
# embedded: scripts/build_template_variants.py
# ======================================================================
SOURCES['build_template_variants'] = r'''#!/usr/bin/env python3
"""Generate colour-skin templates from one base template.

A variant is the *same* markup as its base template in a fixed default palette:
no CSS is forked, no placeholder is added, only the manifest's `default_palette`
differs. That keeps "adhere to the template, change only the colour" true by
construction -- edit the base template once and re-run this to refresh every skin.

    python scripts/build_template_variants.py                    # use the spec below
    python scripts/build_template_variants.py --list             # show current skins
    python scripts/build_template_variants.py --prune            # delete skins no longer in the spec

The spec lives in assets/templates/<base>/variants.json so it is data, not code:

    { "base": "technext-shell",
      "skins": [{"palette": "ocean", "label": "TechNext Shell - Ocean",
                 "label_vi": "TechNext Shell - Xanh dai duong"}, ...] }
"""

from __future__ import annotations

import argparse
import io
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "assets" / "templates"
PALETTES = ROOT / "assets" / "palettes.json"
SPEC_NAME = "variants.json"


def load_json(path):
    return json.loads(path.read_text(encoding="utf-8-sig"))


def find_entry(folder):
    for name in ("template.html", "index.html", "template.htm", "index.htm"):
        candidate = folder / name
        if candidate.is_file():
            return candidate
    files = sorted(p for p in folder.rglob("*.htm*") if p.is_file())
    if not files:
        raise FileNotFoundError("no .html entry in %s" % folder)
    return files[0]


def variant_id(base_id, palette):
    return "%s-%s" % (base_id, palette)


def build(base_id, skin, palettes, base_manifest, markup, prune=False):
    palette = skin["palette"]
    if palette not in palettes:
        raise KeyError("unknown palette %r (available: %s)"
                       % (palette, ", ".join(sorted(palettes))))
    vid = variant_id(base_id, palette)
    folder = TEMPLATES / vid
    folder.mkdir(parents=True, exist_ok=True)
    entry_name = base_manifest.get("entry") or "template.html"
    (folder / entry_name).write_text(markup, encoding="utf-8", newline="\n")

    pal_meta = palettes[palette]
    label = skin.get("label") or "%s - %s" % (base_manifest.get("label") or base_id,
                                              pal_meta.get("label") or palette)
    manifest = {
        "id": vid,
        "label": label,
        "label_vi": skin.get("label_vi") or label,
        "description": skin.get("description") or
            "%s, shipped in the %s palette." % (base_manifest.get("description") or "", palette),
        "use_when": skin.get("use_when") or base_manifest.get("use_when") or "",
        "doc_types": base_manifest.get("doc_types") or [],
        "default_palette": palette,
        "entry": entry_name,
        "variant_of": base_id,
    }
    (folder / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    return vid, entry_name


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate colour-skin templates from a base template.")
    parser.add_argument("--base", default="", help="base template id (default: the one with variants.json)")
    parser.add_argument("--list", action="store_true", help="show the skins that exist now")
    parser.add_argument("--prune", action="store_true", help="delete skins not in the spec")
    parser.add_argument("--templates", default="", help="templates folder")
    args = parser.parse_args(argv)

    templates_dir = Path(args.templates).expanduser() if args.templates else TEMPLATES
    palettes = load_json(PALETTES).get("palettes") or {}

    specs = []
    for folder in sorted(p for p in templates_dir.iterdir() if p.is_dir()):
        spec_path = folder / SPEC_NAME
        if spec_path.is_file():
            specs.append((folder.name, load_json(spec_path)))
    if not specs:
        print("error: no %s found under %s" % (SPEC_NAME, templates_dir), file=sys.stderr)
        return 2
    if args.base:
        specs = [s for s in specs if s[0] == args.base]
        if not specs:
            print("error: no spec for base %r" % args.base, file=sys.stderr)
            return 2

    if args.list:
        for base_id, spec in specs:
            print("%s:" % base_id)
            for skin in spec.get("skins") or []:
                vid = variant_id(base_id, skin["palette"])
                mark = "ok " if (templates_dir / vid).is_dir() else "MISSING"
                print("  %-7s %-28s <- palette %s" % (mark, vid, skin["palette"]))
        return 0

    total = 0
    for base_id, spec in specs:
        base_folder = templates_dir / base_id
        base_manifest = load_json(base_folder / "manifest.json")
        markup = find_entry(base_folder).read_text(encoding="utf-8")
        wanted = set()
        for skin in spec.get("skins") or []:
            vid, _entry = build(base_id, skin, palettes, base_manifest, markup)
            wanted.add(vid)
            print("  wrote %-28s default_palette=%s" % (vid, skin["palette"]))
            total += 1
        if args.prune:
            for folder in sorted(p for p in templates_dir.iterdir() if p.is_dir()):
                if not folder.name.startswith(base_id + "-"):
                    continue
                try:
                    if load_json(folder / "manifest.json").get("variant_of") != base_id:
                        continue
                except (OSError, json.JSONDecodeError):
                    continue
                if folder.name not in wanted:
                    shutil.rmtree(folder)
                    print("  pruned %s" % folder.name)
    print("\n%d skin(s) across %d base template(s)" % (total, len(specs)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

# ---------------------------------------------------------------- launcher

import hashlib as _hashlib
import json as _json
import os as _os
import sys as _sys
import tempfile as _tempfile
import types as _types
from pathlib import Path as _Path

HERE = _Path(__file__).resolve().parent
BUNDLE = HERE.parent / "assets" / "bundle.json"
COMMANDS = {'import': 'import_doc', 'render': 'render_doc', 'validate': 'validate_output', 'palette': 'custom_palette', 'preview': 'preview_sheet', 'scan': 'scan_templates', 'skins': 'build_template_variants'}
USAGE = """usage: python scripts/docstyler.py <command> [options]

commands:
  import    source .md/.txt/.docx -> model JSON + outline   (--outline m.json to only print)
  render    model -> HTML          (--template <id|folder>, --palette <name> | --palette-file)
  validate  check a rendered HTML  (--require-palette --model m.json)
  palette   colours the user names -> palette JSON
  preview   one page comparing templates/palettes for the user's document
  scan      list templates with their placeholders and colour variables
  editor    write the browser editor:  editor --out <file.html>
  templates print the folder holding the unpacked templates

run `<command> --help` for the options of each."""


def _cache_root():
    """Unpack assets/bundle.json once per bundle version. Only ever writes
    under the system temp directory."""
    raw = BUNDLE.read_bytes()
    root = _Path(_tempfile.gettempdir()) / ("doc-template-styler-" + _hashlib.sha256(raw).hexdigest()[:12])
    stamp = root / ".complete"
    if stamp.is_file():
        return root
    bundle = _json.loads(raw.decode("utf-8"))
    templates = root / "assets" / "templates"
    for tid, entry in bundle["templates"].items():
        folder = templates / tid
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "template.html").write_text(entry["html"], encoding="utf-8")
        (folder / "manifest.json").write_text(_json.dumps(entry["manifest"], ensure_ascii=False, indent=2), encoding="utf-8")
        if entry.get("variants"):
            (folder / "variants.json").write_text(_json.dumps(entry["variants"], ensure_ascii=False, indent=2), encoding="utf-8")
    (root / "assets" / "palettes.json").write_text(_json.dumps(bundle["palettes"], ensure_ascii=False, indent=2), encoding="utf-8")
    (root / "scripts").mkdir(parents=True, exist_ok=True)
    _load("build_template_variants", root)
    import io as _io
    from contextlib import redirect_stdout as _redirect
    with _redirect(_io.StringIO()):
        _sys.modules["build_template_variants"].main([])
    stamp.write_text("ok", encoding="utf-8")
    return root


def _load(name, root):
    if name in _sys.modules and getattr(_sys.modules[name], "__docstyler__", False):
        return _sys.modules[name]
    module = _types.ModuleType(name)
    # the scripts find the skill root as Path(__file__).parent.parent
    module.__file__ = str(root / "scripts" / (name + ".py"))
    module.__docstyler__ = True
    _sys.modules[name] = module
    exec(compile(SOURCES[name], name + ".py", "exec"), module.__dict__)
    return module


def _resolve_templates(argv, root):
    """--template <id> means a bundled template; a path stays a path."""
    out = list(argv)
    for i, arg in enumerate(out[:-1]):
        if arg == "--template" and not _Path(out[i + 1]).exists():
            candidate = root / "assets" / "templates" / out[i + 1]
            if candidate.is_dir():
                out[i + 1] = str(candidate)
    return out


def main(argv=None):
    argv = list(_sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ("-h", "--help", "help"):
        print(USAGE)
        return 0
    command, rest = argv[0], argv[1:]
    root = _cache_root()
    templates_dir = str(root / "assets" / "templates")
    if command == "templates":
        print(templates_dir)
        return 0
    if command == "editor":
        if "--out" not in rest or rest.index("--out") == len(rest) - 1:
            print("usage: docstyler.py editor --out <file.html>", file=_sys.stderr)
            return 2
        target = _Path(rest[rest.index("--out") + 1])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_json.loads(BUNDLE.read_text(encoding="utf-8"))["editor"], encoding="utf-8")
        print("wrote %s - open it in a browser" % target)
        return 0
    if command not in COMMANDS:
        print("unknown command %r\n\n%s" % (command, USAGE), file=_sys.stderr)
        return 2
    rest = _resolve_templates(rest, root)
    if command in ("preview", "skins") and "--templates" not in rest:
        rest += ["--templates", templates_dir]
    if command == "scan" and not [a for a in rest if not a.startswith("-")]:
        rest = [templates_dir] + rest
    for name in ['render_doc', 'import_doc', 'validate_output', 'custom_palette', 'preview_sheet', 'scan_templates', 'build_template_variants']:
        _load(name, root)
    return _sys.modules[COMMANDS[command]].main(rest)


if __name__ == "__main__":
    raise SystemExit(main())
